# Generated by Django 4.2.17 on 2025-01-02 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="环境名称")),
                ("base_url", models.URLField(verbose_name="基础URL")),
                ("description", models.TextField(blank=True, verbose_name="环境描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_environments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environments",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试环境",
                "verbose_name_plural": "测试环境",
                "ordering": ["-created_time"],
                "unique_together": {("name", "project")},
            },
        ),
        migrations.CreateModel(
            name="EnvironmentVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="变量名")),
                ("value", models.TextField(verbose_name="变量值")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("string", "字符串"),
                            ("integer", "整数"),
                            ("float", "浮点数"),
                            ("boolean", "布尔值"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                        verbose_name="变量类型",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(default=False, verbose_name="是否敏感数据"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="environments.environment",
                        verbose_name="所属环境",
                    ),
                ),
            ],
            options={
                "verbose_name": "环境变量",
                "verbose_name_plural": "环境变量",
                "ordering": ["name"],
                "unique_together": {("environment", "name")},
            },
        ),
    ]
