# Generated by Django 4.2.17 on 2025-01-08 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="environments.environment",
                verbose_name="父环境",
            ),
        ),
    ]
