# Generated by Django 4.2.14 on 2025-02-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0002_environment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="verify_ssl",
            field=models.BooleanField(default=True, verbose_name="验证SSL证书"),
        ),
        migrations.AlterField(
            model_name="environmentvariable",
            name="type",
            field=models.CharField(
                choices=[
                    ("string", "字符串"),
                    ("integer", "整数"),
                    ("float", "浮点数"),
                    ("boolean", "布尔值"),
                    ("json", "JSON对象"),
                    ("list", "列表"),
                    ("dict", "字典"),
                ],
                default="string",
                max_length=20,
                verbose_name="变量类型",
            ),
        ),
    ]
