# Generated by Django 4.2.17 on 2025-04-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database_configs", "0001_initial"),
        ("environments", "0005_environment_database_config"),
    ]

    operations = [
        # 列已经存在，跳过这个操作
        # migrations.AddField(
        #     model_name="environment",
        #     name="database_config",
        #     field=models.ForeignKey(
        #         blank=True,
        #         null=True,
        #         on_delete=django.db.models.deletion.SET_NULL,
        #         related_name="environments",
        #         to="database_configs.databaseconfig",
        #         verbose_name="数据库配置",
        #     ),
        # ),
    ]
