# Generated by Django 4.2.17 on 2025-04-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database_configs", "0003_databaseconfig_connection_params_and_more"),
        ("environments", "0006_environment_database_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="database_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="environments",
                to="database_configs.databaseconfig",
                verbose_name="数据库配置",
            ),
        ),
    ]
