# Generated by Django 4.2.17 on 2024-12-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='手机号（可选）', max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
