FROM ghcr.io/lucky-testrunner/testrunner-backend:latest

# 安装所有必需的Python包
RUN pip install --upgrade pip && \
    pip install simpleui import_export drf-yasg django-filter djangorestframework-simplejwt

# 设置工作目录
WORKDIR /app

# 复制项目文件
COPY ./TestRunner_Django/ /app/

# 确保日志目录存在
RUN mkdir -p /app/logs

# 运行迁移和启动命令
CMD ["sh", "-c", "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"]
