# Generated by Django 4.2.17 on 2025-01-04 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
        ("environments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="接口名称")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                            ("PATCH", "PATCH"),
                        ],
                        max_length=20,
                        verbose_name="请求方法",
                    ),
                ),
                ("url", models.TextField(verbose_name="接口地址")),
                ("headers", models.JSONField(default=dict, verbose_name="请求头")),
                ("params", models.JSONField(default=dict, verbose_name="查询参数")),
                ("body", models.JSONField(default=dict, verbose_name="请求体")),
                (
                    "validators",
                    models.JSONField(
                        default=list,
                        help_text='[{"check": "status_code", "expect": 200}]',
                        verbose_name="断言规则",
                    ),
                ),
                (
                    "extract",
                    models.JSONField(
                        default=dict,
                        help_text='{"token": "body.data.token"}',
                        verbose_name="提取变量",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_interfaces",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interfaces",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "接口",
                "verbose_name_plural": "接口",
                "ordering": ["-created_time"],
                "unique_together": {("name", "project")},
            },
        ),
        migrations.CreateModel(
            name="InterfaceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(verbose_name="执行状态")),
                ("elapsed", models.FloatField(verbose_name="响应时间(ms)")),
                ("request", models.JSONField(verbose_name="请求信息")),
                ("response", models.JSONField(verbose_name="响应信息")),
                (
                    "validation_results",
                    models.JSONField(default=list, verbose_name="断言结果"),
                ),
                (
                    "extracted_variables",
                    models.JSONField(default=dict, verbose_name="提取的变量"),
                ),
                (
                    "executed_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="执行时间"),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interface_results",
                        to="environments.environment",
                        verbose_name="执行环境",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="interfaces.interface",
                        verbose_name="关联接口",
                    ),
                ),
            ],
            options={
                "verbose_name": "接口执行结果",
                "verbose_name_plural": "接口执行结果",
                "ordering": ["-executed_time"],
            },
        ),
    ]
