# Generated by Django 4.2.17 on 2025-01-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0001_initial"),
        ("interfaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interface",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interfaces",
                to="modules.module",
                verbose_name="所属模块",
            ),
        ),
    ]
