# Generated by Django 4.2.17 on 2025-01-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interfaces", "0002_interface_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="interface",
            name="setup_hooks",
            field=models.JSONField(
                default=list,
                help_text='["${setup_hook_prepare_kwargs($request)}"]',
                verbose_name="前置钩子",
            ),
        ),
        migrations.AddField(
            model_name="interface",
            name="teardown_hooks",
            field=models.JSONField(
                default=list,
                help_text='["${teardown_hook_sleep_N_secs($response, 2)}"]',
                verbose_name="后置钩子",
            ),
        ),
        migrations.AddField(
            model_name="interface",
            name="variables",
            field=models.JSONField(
                default=dict,
                help_text='{"username": "testuser", "password": "123456"}',
                verbose_name="变量",
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="validators",
            field=models.JSONField(
                default=list,
                help_text='[{"eq": ["status_code", 200]}]',
                verbose_name="断言规则",
            ),
        ),
    ]
