# Generated by Django 4.2.17 on 2025-04-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interfaces", "0003_interface_setup_hooks_interface_teardown_hooks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interface",
            name="sql",
            field=models.TextField(blank=True, null=True, verbose_name="SQL语句"),
        ),
        migrations.AddField(
            model_name="interface",
            name="sql_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fetchone", "查询单条"),
                    ("fetchmany", "查询多条"),
                    ("fetchall", "查询所有"),
                    ("insert", "插入"),
                    ("update", "更新"),
                    ("delete", "删除"),
                ],
                max_length=20,
                null=True,
                verbose_name="SQL方法",
            ),
        ),
        migrations.AddField(
            model_name="interface",
            name="sql_params",
            field=models.JSONField(blank=True, default=dict, verbose_name="SQL参数"),
        ),
        migrations.AddField(
            model_name="interface",
            name="sql_size",
            field=models.IntegerField(
                blank=True, default=10, help_text="仅用于fetchmany方法", verbose_name="查询条数"
            ),
        ),
        migrations.AddField(
            model_name="interface",
            name="type",
            field=models.CharField(
                choices=[("http", "HTTP接口"), ("sql", "SQL接口")],
                default="http",
                max_length=20,
                verbose_name="接口类型",
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="body",
            field=models.JSONField(blank=True, default=dict, verbose_name="请求体"),
        ),
        migrations.AlterField(
            model_name="interface",
            name="extract",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"token": "body.data.token"}',
                verbose_name="提取变量",
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="headers",
            field=models.JSONField(blank=True, default=dict, verbose_name="请求头"),
        ),
        migrations.AlterField(
            model_name="interface",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GET", "GET"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("DELETE", "DELETE"),
                    ("PATCH", "PATCH"),
                ],
                max_length=20,
                null=True,
                verbose_name="请求方法",
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="params",
            field=models.JSONField(blank=True, default=dict, verbose_name="查询参数"),
        ),
        migrations.AlterField(
            model_name="interface",
            name="setup_hooks",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='["${setup_hook_prepare_kwargs($request)}"]',
                verbose_name="前置钩子",
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="teardown_hooks",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='["${teardown_hook_sleep_N_secs($response, 2)}"]',
                verbose_name="后置钩子",
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="url",
            field=models.TextField(blank=True, null=True, verbose_name="接口地址"),
        ),
        migrations.AlterField(
            model_name="interface",
            name="validators",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[{"eq": ["status_code", 200]}]',
                verbose_name="断言规则",
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="variables",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"username": "testuser", "password": "123456"}',
                verbose_name="变量",
            ),
        ),
    ]
