# Generated by Django 4.2.11 on 2025-11-05 06:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pythontool", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Script",
            new_name="Tool",
        ),
        migrations.RenameModel(
            old_name="ScriptDependency",
            new_name="Tools",
        ),
    ]
