# Generated by Django 4.2.11 on 2025-11-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pythontool", "0002_rename_script_tool_rename_scriptdependency_tools"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tool",
            options={
                "ordering": ["-create_time"],
                "verbose_name": "Python工具",
                "verbose_name_plural": "Python工具",
            },
        ),
        migrations.AlterModelOptions(
            name="tools",
            options={
                "ordering": ["-create_time"],
                "verbose_name": "脚本依赖工具",
                "verbose_name_plural": "脚本依赖工具",
            },
        ),
        migrations.RenameField(
            model_name="tool",
            old_name="created_at",
            new_name="create_time",
        ),
        migrations.RenameField(
            model_name="tool",
            old_name="updated_at",
            new_name="updated_time",
        ),
        migrations.RenameField(
            model_name="tools",
            old_name="created_at",
            new_name="create_time",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="content",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="project",
        ),
        migrations.RemoveField(
            model_name="tools",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tools",
            name="url",
        ),
        migrations.RemoveField(
            model_name="tools",
            name="version",
        ),
        migrations.AddField(
            model_name="tool",
            name="connect_pools",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="连接池配置"
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="creator",
            field=models.CharField(default="朱若轩", max_length=255, verbose_name="创建人"),
        ),
        migrations.AddField(
            model_name="tool",
            name="params",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="参数配置"
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="pythonScript",
            field=models.TextField(blank=True, null=True, verbose_name="Python脚本"),
        ),
        migrations.AddField(
            model_name="tool",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="工具备注"),
        ),
        migrations.AddField(
            model_name="tools",
            name="pythonScript",
            field=models.TextField(blank=True, null=True, verbose_name="Python脚本"),
        ),
        migrations.AddField(
            model_name="tools",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="工具备注"),
        ),
        migrations.AlterField(
            model_name="tool",
            name="name",
            field=models.CharField(max_length=100, verbose_name="工具名称"),
        ),
        migrations.AlterField(
            model_name="tools",
            name="name",
            field=models.CharField(max_length=255, verbose_name="工具名称"),
        ),
    ]
