# Generated by Django 4.2.11 on 2025-12-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pythontool", "0004_alter_tool_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="group_name",
            field=models.CharField(
                default="未分组", max_length=100, verbose_name="工具分组名称"
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(fields=["name"], name="pythontool__name_23d6f9_idx"),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["group_name"], name="pythontool__group_n_ebffba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["create_time"], name="pythontool__create__0773b3_idx"
            ),
        ),
    ]
