# Generated by Django 4.2.14 on 2025-03-07 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("testcases", "0005_remove_testcase_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interfaces", "0003_interface_setup_hooks_interface_teardown_hooks_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                ("description", models.TextField(blank=True, verbose_name="配置描述")),
                (
                    "sync_fields",
                    models.JSONField(
                        default=list, help_text="配置需要同步的字段列表", verbose_name="同步字段"
                    ),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "sync_mode",
                    models.CharField(
                        choices=[("manual", "手动同步"), ("auto", "自动同步")],
                        default="manual",
                        max_length=20,
                        verbose_name="同步模式",
                    ),
                ),
                (
                    "sync_trigger",
                    models.JSONField(
                        default=dict, help_text="自动同步的触发条件配置", verbose_name="触发条件"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sync_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_configs",
                        to="interfaces.interface",
                        verbose_name="关联接口",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_configs",
                        to="testcases.testcasestep",
                        verbose_name="关联步骤",
                    ),
                ),
                (
                    "testcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_configs",
                        to="testcases.testcase",
                        verbose_name="关联用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "同步配置",
                "verbose_name_plural": "同步配置",
                "ordering": ["-updated_time"],
                "unique_together": {("interface", "testcase", "step")},
            },
        ),
        migrations.CreateModel(
            name="SyncHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("manual", "手动同步"),
                            ("auto", "自动同步"),
                            ("batch", "批量同步"),
                        ],
                        max_length=20,
                        verbose_name="同步类型",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("partial", "部分成功"),
                        ],
                        max_length=20,
                        verbose_name="同步状态",
                    ),
                ),
                (
                    "sync_fields",
                    models.JSONField(help_text="本次同步的字段列表", verbose_name="同步字段"),
                ),
                ("old_data", models.JSONField(verbose_name="同步前数据")),
                ("new_data", models.JSONField(verbose_name="同步后数据")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "sync_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="同步时间"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "sync_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_histories",
                        to="sync.syncconfig",
                        verbose_name="同步配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "同步历史",
                "verbose_name_plural": "同步历史",
                "ordering": ["-sync_time"],
            },
        ),
    ]
