# Generated by Django 4.2.14 on 2025-03-07 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSyncConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                ("description", models.TextField(blank=True, verbose_name="配置描述")),
                (
                    "sync_fields",
                    models.JSONField(
                        default=list, help_text="配置需要同步的字段列表", verbose_name="同步字段"
                    ),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "sync_mode",
                    models.CharField(
                        choices=[("manual", "手动同步"), ("auto", "自动同步")],
                        default="manual",
                        max_length=20,
                        verbose_name="同步模式",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="只能有一个配置处于激活状态", verbose_name="是否激活"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_global_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "全局同步配置",
                "verbose_name_plural": "全局同步配置",
                "ordering": ["-updated_time"],
            },
        ),
    ]
