# Generated by Django 4.2.14 on 2025-03-07 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("sync", "0002_globalsyncconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsyncconfig",
            name="project",
            field=models.ForeignKey(
                default=161,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="global_sync_configs",
                to="projects.project",
                verbose_name="所属项目",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="globalsyncconfig",
            unique_together={("project", "name")},
        ),
    ]
