# Generated by Django 4.2.17 on 2025-04-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database_configs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaseconfig",
            name="db_type",
            field=models.CharField(
                choices=[
                    ("mysql", "MySQL"),
                    ("postgresql", "PostgreSQL"),
                    ("sqlite", "SQLite"),
                    ("oracle", "Oracle"),
                    ("sqlserver", "SQL Server"),
                ],
                default="mysql",
                max_length=20,
                verbose_name="数据库类型",
            ),
        ),
    ]
