# Generated by Django 4.2.17 on 2025-04-05 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database_configs", "0002_databaseconfig_db_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaseconfig",
            name="connection_params",
            field=models.JSONField(blank=True, default=dict, verbose_name="连接参数"),
        ),
        migrations.AddField(
            model_name="databaseconfig",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_database_configs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="databaseconfig",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="databaseconfig",
            name="psm",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="PSM"
            ),
        ),
        migrations.AddField(
            model_name="databaseconfig",
            name="verify_ssl",
            field=models.BooleanField(default=False, verbose_name="验证SSL"),
        ),
    ]
