# Generated by Django 4.2.14 on 2025-03-03 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testcases", "0005_remove_testcase_module"),
        ("projects", "0001_initial"),
        ("environments", "0003_environment_verify_ssl_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestTaskSuite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任务集名称")),
                ("description", models.TextField(blank=True, verbose_name="任务集描述")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("P0", "P0 - 最高"),
                            ("P1", "P1 - 较高"),
                            ("P2", "P2 - 普通"),
                            ("P3", "P3 - 较低"),
                        ],
                        default="P2",
                        help_text="P0: 核心功能，P1: 重要功能，P2: 一般功能，P3: 边缘功能",
                        max_length=2,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "fail_fast",
                    models.BooleanField(
                        default=False,
                        help_text="当一个用例执行失败时，是否停止执行后续用例",
                        verbose_name="快速失败",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_task_suites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_task_suites",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试任务集",
                "verbose_name_plural": "测试任务集",
                "ordering": ["-created_time"],
                "unique_together": {("name", "project")},
            },
        ),
        migrations.CreateModel(
            name="TestTaskExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "执行失败"),
                            ("canceled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                ("total_count", models.IntegerField(default=0, verbose_name="总用例数")),
                ("success_count", models.IntegerField(default=0, verbose_name="成功用例数")),
                ("fail_count", models.IntegerField(default=0, verbose_name="失败用例数")),
                ("error_count", models.IntegerField(default=0, verbose_name="错误用例数")),
                (
                    "task_id",
                    models.CharField(blank=True, max_length=100, verbose_name="任务ID"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_executions",
                        to="environments.environment",
                        verbose_name="执行环境",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "task_suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="testtasks.testtasksuite",
                        verbose_name="任务集",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务执行记录",
                "verbose_name_plural": "任务执行记录",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="TestTaskCaseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failure", "失败"),
                            ("error", "错误"),
                            ("skipped", "已跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                ("duration", models.FloatField(default=0, verbose_name="执行时长(s)")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_results",
                        to="testtasks.testtaskexecution",
                        verbose_name="执行记录",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_results",
                        to="testcases.testreport",
                        verbose_name="测试报告",
                    ),
                ),
                (
                    "testcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_results",
                        to="testcases.testcase",
                        verbose_name="测试用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "用例执行结果",
                "verbose_name_plural": "用例执行结果",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TestTaskCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="执行顺序")),
                (
                    "task_suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_cases",
                        to="testtasks.testtasksuite",
                        verbose_name="所属任务集",
                    ),
                ),
                (
                    "testcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_cases",
                        to="testcases.testcase",
                        verbose_name="测试用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务用例关联",
                "verbose_name_plural": "任务用例关联",
                "ordering": ["order"],
                "unique_together": {("task_suite", "testcase")},
            },
        ),
    ]
