# Generated by Django 4.2.14 on 2025-01-17 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("interfaces", "0003_interface_setup_hooks_interface_teardown_hooks_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="用例名称")),
                ("description", models.TextField(blank=True, verbose_name="用例描述")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("P0", "P0"),
                            ("P1", "P1"),
                            ("P2", "P2"),
                            ("P3", "P3"),
                        ],
                        default="P2",
                        max_length=2,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text={
                            "base_url": "基础URL",
                            "export": "导出变量列表",
                            "parameters": "参数化数据",
                            "variables": "变量配置",
                            "verify": "SSL验证",
                        },
                        verbose_name="用例配置",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_testcases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testcases",
                        to="modules.module",
                        verbose_name="所属模块",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcases",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例",
                "verbose_name_plural": "测试用例",
                "ordering": ["-created_time"],
                "unique_together": {("name", "project")},
            },
        ),
        migrations.CreateModel(
            name="TestCaseStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="步骤名称")),
                ("order", models.IntegerField(verbose_name="执行顺序")),
                (
                    "interface_data",
                    models.JSONField(
                        help_text={
                            "body": "请求体",
                            "extract": "变量提取",
                            "headers": "请求头",
                            "method": "请求方法",
                            "params": "查询参数",
                            "setup_hooks": "前置钩子",
                            "teardown_hooks": "后置钩子",
                            "url": "接口地址",
                            "validators": "断言规则",
                            "variables": "变量",
                        },
                        verbose_name="接口数据",
                    ),
                ),
                (
                    "sync_fields",
                    models.JSONField(
                        default=list,
                        help_text='["url", "headers", "body"]',
                        verbose_name="同步字段配置",
                    ),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后同步时间"),
                ),
                (
                    "origin_interface",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_steps",
                        to="interfaces.interface",
                        verbose_name="关联接口",
                    ),
                ),
                (
                    "testcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="testcases.testcase",
                        verbose_name="所属用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试步骤",
                "verbose_name_plural": "测试步骤",
                "ordering": ["order"],
                "unique_together": {("testcase", "order")},
            },
        ),
    ]
