# Generated by Django 4.2.14 on 2025-01-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcasestep",
            name="sync_fields",
            field=models.JSONField(
                default=list,
                help_text=[
                    "method",
                    "url",
                    "headers",
                    "params",
                    "body",
                    "setup_hooks",
                    "teardown_hooks",
                    "variables",
                    "validators",
                    "extract",
                ],
                verbose_name="同步字段配置",
            ),
        ),
    ]
