# Generated by Django 4.2.14 on 2025-01-17 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0002_environment_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testcases", "0002_alter_testcasestep_sync_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="报告名称")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failure", "失败"), ("error", "错误")],
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                ("success_count", models.IntegerField(default=0, verbose_name="成功步骤数")),
                ("fail_count", models.IntegerField(default=0, verbose_name="失败步骤数")),
                ("error_count", models.IntegerField(default=0, verbose_name="错误步骤数")),
                ("duration", models.FloatField(verbose_name="执行时长(s)")),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "summary",
                    models.JSONField(
                        help_text={
                            "in_out": {"config_vars": "配置变量", "export_vars": "导出变量"},
                            "log": "执行日志",
                            "name": "用例名称",
                            "success": "是否成功",
                            "time": {"duration": "执行时长", "start_at": "开始时间"},
                        },
                        verbose_name="执行汇总",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="environments.environment",
                        verbose_name="执行环境",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "testcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="testcases.testcase",
                        verbose_name="关联用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试报告",
                "verbose_name_plural": "测试报告",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="TestReportDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField(verbose_name="是否成功")),
                ("elapsed", models.FloatField(verbose_name="执行时长(ms)")),
                (
                    "request",
                    models.JSONField(
                        help_text={
                            "body": "请求体",
                            "headers": "请求头",
                            "method": "请求方法",
                            "url": "请求地址",
                        },
                        verbose_name="请求信息",
                    ),
                ),
                (
                    "response",
                    models.JSONField(
                        help_text={
                            "body": "响应体",
                            "content_size": "响应大小",
                            "headers": "响应头",
                            "response_time_ms": "响应时间",
                            "status_code": "状态码",
                        },
                        verbose_name="响应信息",
                    ),
                ),
                ("validators", models.JSONField(default=list, verbose_name="断言结果")),
                (
                    "extracted_variables",
                    models.JSONField(default=dict, verbose_name="提取的变量"),
                ),
                ("attachment", models.TextField(blank=True, verbose_name="附加信息")),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="testcases.testreport",
                        verbose_name="测试报告",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="testcases.testcasestep",
                        verbose_name="测试步骤",
                    ),
                ),
            ],
            options={
                "verbose_name": "报告详情",
                "verbose_name_plural": "报告详情",
                "ordering": ["id"],
            },
        ),
    ]
