# Generated by Django 4.2.14 on 2025-01-17 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testcases", "0003_testreport_testreportdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="priority",
            field=models.CharField(
                choices=[
                    ("P0", "P0 - 最高"),
                    ("P1", "P1 - 较高"),
                    ("P2", "P2 - 普通"),
                    ("P3", "P3 - 较低"),
                ],
                default="P2",
                help_text="P0: 核心功能，P1: 重要功能，P2: 一般功能，P3: 边缘功能",
                max_length=2,
                verbose_name="优先级",
            ),
        ),
        migrations.AlterField(
            model_name="testreportdetail",
            name="response",
            field=models.JSONField(
                help_text={
                    "body": "响应体",
                    "content_size": "响应大小",
                    "headers": "响应头",
                    "response_time": "响应时间",
                    "status_code": "状态码",
                },
                verbose_name="响应信息",
            ),
        ),
        migrations.CreateModel(
            name="TestCaseTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="标签名称")),
                (
                    "color",
                    models.CharField(
                        default="#1890ff",
                        help_text="标签显示的颜色，例如：#1890ff",
                        max_length=20,
                        verbose_name="标签颜色",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcase_tags",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "用例标签",
                "verbose_name_plural": "用例标签",
                "ordering": ["name"],
                "unique_together": {("name", "project")},
            },
        ),
        migrations.CreateModel(
            name="TestCaseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分组名称")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="testcases.testcasegroup",
                        verbose_name="父分组",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcase_groups",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "用例分组",
                "verbose_name_plural": "用例分组",
                "ordering": ["name"],
                "unique_together": {("name", "parent", "project")},
            },
        ),
        migrations.AddField(
            model_name="testcase",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="testcases",
                to="testcases.testcasegroup",
                verbose_name="所属分组",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="testcases",
                to="testcases.testcasetag",
                verbose_name="标签",
            ),
        ),
    ]
