# Generated by Django 4.2.14 on 2025-01-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0004_alter_testcase_priority_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="module",
        ),
    ]
